services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "3000:3000/tcp"
    restart: unless-stopped
    volumes:
      - adguardhome_data:/opt/adguardhome/data

volumes:
    adguardhome_data: