services:
  mailserver:
    container_name: mailserver
    image: mailserver/docker-mailserver:latest
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.tessmann.internal
    ports:
      - "25:25"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PERMIT_DOCKER=connected-networks
      - TZ=Europe/Berlin
      - ENABLE_AMAVIS=0
      - ENABLE_DNSBL=0
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_POP3=0
      - ENABLE_IMAP=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - SPOOF_PROTECTION=0
      - ENABLE_SRS=0
      - ENABLE_QUOTAS=0
      - POSTMASTER_ADDRESS=postmaster@tessmann.internal
      - ENABLE_UPDATE_CHECK=1
      - UPDATE_CHECK_INTERVAL=1d
      - ENABLE_RSPAMD=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_FETCHMAIL=0
      - ENABLE_GETMAIL=0
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
    restart: always